# Generated by Django 5.2.7 on 2025-12-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmember_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='project_id',
            new_name='project',
        ),
    ]
