# Generated by Django 5.2.7 on 2025-12-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_project_id_projectmember_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'verbose_name': 'Project Member', 'verbose_name_plural': 'Project Members'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Project Story', 'verbose_name_plural': 'Project Stories'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='Projects',
        ),
        migrations.AlterModelTable(
            name='projectmember',
            table='Project_Members',
        ),
        migrations.AlterModelTable(
            name='story',
            table='Project_Stories',
        ),
    ]
