# Generated by Django 5.2.7 on 2025-12-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_rename_city_id_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-created_at']},
        ),
    ]
