# Generated by Django 5.2.7 on 2025-12-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_alter_address_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='Addresses',
        ),
        migrations.AlterModelTable(
            name='city',
            table='Cities',
        ),
        migrations.AlterModelTable(
            name='country',
            table='Countries',
        ),
        migrations.AlterModelTable(
            name='state',
            table='States',
        ),
    ]
