# Generated by Django 5.2.7 on 2025-12-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_member_id',
            new_name='assigned_member',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='story_id',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='ticketattachment',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='tickethistory',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
