# Generated by Django 5.2.7 on 2025-12-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_assigned_member_id_ticket_assigned_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ['-created_at']},
        ),
    ]
