# Generated by Django 5.2.7 on 2025-12-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_options_alter_ticketattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'verbose_name': 'Ticket Attachment', 'verbose_name_plural': 'Ticket Attachments'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'verbose_name': 'Ticket Comment', 'verbose_name_plural': 'Ticket Comments'},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'verbose_name': 'Ticket History', 'verbose_name_plural': 'Ticket Histories'},
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='Tickets',
        ),
        migrations.AlterModelTable(
            name='ticketattachment',
            table='Ticket_Attachments',
        ),
        migrations.AlterModelTable(
            name='ticketcomment',
            table='Ticket_Comments',
        ),
        migrations.AlterModelTable(
            name='tickethistory',
            table='Ticket_Histories',
        ),
    ]
