# Generated by Django 5.2.7 on 2025-12-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_start_date'),
        ('tickets', '0004_alter_ticket_options_alter_ticketattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='projects.projectmember'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='projects.story'),
        ),
    ]
